apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-gdam
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-gdam
    app.kubernetes.io/part-of: first-app
  name: devfile-sample-python-basic-gdam
  namespace: rbohne-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-gdam
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-gdam
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:c65259cb30cf8d3eb9bf3eac02c072803f3c6cb9d977542accae285285a26f57
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
